export enum Event {
  TEST = 'TEST',
  CREATE_USER = 'CREATE_USER',
  LIST_USERS = 'LIST_USERS',
  LIST_USER_BY_ID = 'LIST_USER_BY_ID',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
}
